name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract versions and metadata
        id: meta
        run: |
          # 提取语义化版本
          VERSION=${GITHUB_REF#refs/tags/v}
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f1-2)
          
          # 生成日期标签 (格式: YYYYMMDD-HHMMSS)
          BUILD_DATE=$(date +'%Y%m%d-%H%M%S')
          
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "major=${MAJOR}" >> $GITHUB_OUTPUT
          echo "minor=${MINOR}" >> $GITHUB_OUTPUT
          echo "date=${BUILD_DATE}" >> $GITHUB_OUTPUT

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name == 'push' }}
          tags: |
            # ${{ secrets.DOCKERHUB_USERNAME }}/mt-auto-free-to-qb:${{ steps.meta.outputs.major }}
            # ${{ secrets.DOCKERHUB_USERNAME }}/mt-auto-free-to-qb:${{ steps.meta.outputs.minor }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mt-auto-free-to-qb:${{ steps.meta.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mt-auto-free-to-qb:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mt-auto-free-to-qb:sha-${{ github.sha }}
            # ${{ secrets.DOCKERHUB_USERNAME }}/mt-auto-free-to-qb:build-${{ steps.meta.outputs.date }}
          labels: |
            org.opencontainers.image.version=${{ steps.meta.outputs.version }}
            org.opencontainers.image.created=${{ steps.meta.outputs.date }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository_url }}
          cache-from: type=gha
          cache-to: type=gha,mode=max